version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

defaults: &defaults
  working_directory: ~/cli
  docker:
    - image: node:latest

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run: npm install
      - run: npm build
      - run: npm test
      - codecov/upload:
          file: coverage/coverage-final.json
  cache:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
          paths:
            - ~/cli/node_modules
            - ~/.npm
            - /usr/local/lib/node_modules
  publish:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run: npm run build
      - run: npm run semantic-release || true

workflows:
  version: 2
  svarog:
    jobs:
      - test
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              only: master
      - cache:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              only: master